spring.application.name=api-gateway
server.port=8765


#Bu sunucuya bilgilerini kaydetmesi için yaziliyor...
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#Uygulamanizda bir DiscoveryClient (örn. Eureka client) varsa, Gateway kayit defterindeki servisleri okur. Her servis için bir route olusturur.
#Spring Cloud Gatewayin servis kesif sistemi (Eureka/Consul vb.) üzerinden kayitli servisleri otomatik olarak routera dönüstürmesini saglar.
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true

#eurokadan aldigi serverlari kucuk harfle cagirabilmek icin yazildi...
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
eureka.instance.instance-id=${spring.application.name}:${server.port}


