spring.application.name=currency-conversion-service
server.port=8100
spring.config.import=optional:configserver:http://localhost:8888
#spring.cloud.config.enabled=false

eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.instance.prefer-ip-address=true

#Bu sunucuya bilgilerini kaydetmesi için yaziliyor...
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

#Tracing isleminin ne kadarini takip etmek istiyoruz. (1 = 100, 0.05 = %5 ini gibi...)
management.tracing.sampling.probability=1.0

#log'un nasil gözükmesini istiyoruz...
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]