spring.application.name=naming-server
server.port=8761

# Uygulama kendini Eurekaya kaydetmez.
eureka.client.register-with-eureka=false

#Uygulama Eurekadan hic bir kayit cekmez.
eureka.client.fetch-registry=false

