spring.application.name=currency-exchange-service
server.port=8000
spring.config.import=optional:configserver:http://localhost:8888

spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.jpa.show-sql=true
#spring.datasource.url=jdbc:h2:mem:testdb
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true


#Bu sunucuya bilgilerini kaydetmesi için yaziliyor...
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka


# sample-api isimli Retry mekanizmas?n?n en fazla kaç kez deneme yapaca??n? belirtir.
# Bu de?er 5 oldu?u için, ba?ar?s?z olursa toplamda en fazla 5 deneme yap?l?r.
resilience4j.retry.instances.sample-api.maxRetryAttempts=5

# Her retry denemesi aras?nda ne kadar beklenilece?ini belirtir.
# Burada 1s yaz?ld??? için denemeler aras?nda ba?lang?çta 1 saniye beklenir.
resilience4j.retry.instances.sample-api.waitDuration=1s

# Retry denemeleri aras?ndaki bekleme süresinin giderek artmas?n? sa?lar.
# true oldu?u için her ba?ar?s?z denemeden sonra bekleme süresi artarak devam eder.
resilience4j.retry.instances.sample-api.enableExponentialBackoff=true
